# SPDX-License-Identifier: Apache-2.0
"""Ed25519 signing of feeds and channel indexes. Test keys only.

Two roles, after annex §7.2 and §11.1:

- the **namespace** key signs feed.json — the statement of which element
  versions legitimately exist;
- the **channel** key signs a channel index — which of those versions is
  current. It cannot introduce content, because a verifier checks every
  index entry against the namespace-signed feed (S4).

A signature covers the exact bytes of the file, prefixed with a domain
separator naming the role, so a feed signature can never be presented as an
index signature or the other way round.
"""

from __future__ import annotations

import base64
import hashlib
import json
import os
import sys
from pathlib import Path

from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey

KEY_ROLES = ("namespace", "channel")
SIGNED_AS = {"namespace": "feed", "channel": "channel-index"}
DOMAIN = b"qet-protocol signature v1\x00"

TEST_KEY_WARNING = (
    "TEST KEY. Generated by qet-feed keygen on a development machine. It must never sign "
    "anything published: real namespace keys are offline and held under a threshold "
    "(security annex §11.1)."
)


def message(signed_as: str, data: bytes) -> bytes:
    return DOMAIN + signed_as.encode("ascii") + b"\x00" + data


def key_id(public_raw: bytes) -> str:
    return "sha256:" + hashlib.sha256(public_raw).hexdigest()


def _b64(data: bytes) -> str:
    return base64.b64encode(data).decode("ascii")


def _warn() -> None:
    print("qet-feed: WARNING: " + TEST_KEY_WARNING, file=sys.stderr)


def keygen(directory: Path, role: str) -> tuple[Path, Path]:
    """Write <role>.key (private, mode 0600) and <role>.pub."""
    if role not in KEY_ROLES:
        raise ValueError(f"role must be one of {KEY_ROLES}")
    from cryptography.hazmat.primitives.serialization import Encoding, PublicFormat

    private = Ed25519PrivateKey.generate()
    public_raw = private.public_key().public_bytes(Encoding.Raw, PublicFormat.Raw)
    private_raw = private.private_bytes_raw()
    directory.mkdir(parents=True, exist_ok=True)
    key_path, pub_path = directory / f"{role}.key", directory / f"{role}.pub"
    fd = os.open(key_path, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
    with os.fdopen(fd, "w", encoding="utf-8") as fh:
        json.dump({"key": 1, "role": role, "test": True, "warning": TEST_KEY_WARNING,
                   "keyid": key_id(public_raw), "private": _b64(private_raw)}, fh, indent=1)
        fh.write("\n")
    pub_path.write_text(json.dumps({"key": 1, "role": role, "test": True,
                                    "keyid": key_id(public_raw), "public": _b64(public_raw)},
                                   indent=1) + "\n", encoding="utf-8")
    _warn()
    return key_path, pub_path


def load_private(path: Path, role: str) -> tuple[Ed25519PrivateKey, str]:
    doc = json.loads(path.read_text(encoding="utf-8"))
    if doc.get("key") != 1 or doc.get("role") != role:
        raise ValueError(f"{path} is not a {role} key")
    if doc.get("test"):
        _warn()
    private = Ed25519PrivateKey.from_private_bytes(base64.b64decode(doc["private"], validate=True))
    return private, doc["keyid"]


def sign_file(path: Path, private: Ed25519PrivateKey, keyid: str, signed_as: str) -> Path:
    """Write <file>.sig next to the file. Ed25519 is deterministic."""
    sig = private.sign(message(signed_as, path.read_bytes()))
    out = path.with_name(path.name + ".sig")
    out.write_text(json.dumps({"signature": 1, "alg": "ed25519", "role": signed_as,
                               "keyid": keyid, "sig": _b64(sig)}, sort_keys=True, indent=1)
                   + "\n", encoding="utf-8")
    return out


def sign_feed(out: Path, namespace_key: Path, channel_key: Path) -> list[Path]:
    """Sign feed.json with the namespace key and every index with the channel key."""
    ns, ns_id = load_private(namespace_key, "namespace")
    ch, ch_id = load_private(channel_key, "channel")
    written = [sign_file(out / "feed.json", ns, ns_id, SIGNED_AS["namespace"])]
    for index in sorted((out / "index").glob("*.json")):
        written.append(sign_file(index, ch, ch_id, SIGNED_AS["channel"]))
    return written
